### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by luisivan** [dappnode/welcome#1]
![image](https://user-images.githubusercontent.com/718208/59500819-7fb22580-8e9a-11e9-883b-3a607cfb6958.png)

Should be http://my.dappnode/#/devices

Apart from that everything is super smooth, great job!

**Comment by dapplion** [comment]
Thanks for reporting! Fixed with https://github.com/dappnode/welcome/commit/6f286dc43f688f47a45d58bcce4a83f4284015ab
